### ISSUE TITLE
Checklist version SaaS

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#349]
Objectif : booter une nouvelle instance rapidement et pouvoir donner la main aux super-administrateurs du “client final”. Iso-fonctionnel transparent pour l'instance déjà existante "Civils de la Défense".

Organisation :
- [x] Introduire le modèle de base de données "Organization"
- [x] Ajouter les champs nécessaires à la customisation : logo horizontal (en-tête du site Front-Office), logo vertical (pages d'authentification), logo horizontal court (en-tête du site Back-Office), nom (ex "Civils de la Défense"), url (utiliser dans l'envoi de mail), image d'arrière-plan (Front-Office)
- [x] CMS simplifié pour gérer les pages de contenus et les liens (ex: "Mentions Légales", "CGU', etc)

Super-admin 
- [ ] introduire le nouveau rôle "Super-Admin", permet d'accéder (et seulement ce rôle) à tout l'admin y compris à la gestion de l'organisation décrite ci-dessus

Dans un premier temps, l'organisation est une table à une seule entrée par instance, sans relations avec les autres tables.

**Comment by sisitototest** [comment]
Bonjour 
Je souhaite pouvoir utiliser cette version Saas. Ou puis je la récupérer?
Je teste l'installation de la branch production sur scalingo free j'ai systématiquement cette erreure:
 [4/4] Building fresh packages...
       Done in 16.99s.
       rake aborted!
       ArgumentError: bad argument (expected URI object or URI string)
       /build/a6f4cd85-b613-42d4-b42b-2f0843b8fdbf/config/environments/production.rb:68:in `block in <top (required)>'
       /build/a6f4cd85-b613-42d4-b42b-2f0843b8fdbf/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/railtie.rb:216:in `instance_eval'
       /build/a6f4cd85-b613-42d4-b42b


 !
 !     Precompiling assets failed.
 !
 !     An error occured during buildpack compilation
 !   Error deploying the application
 !   → Invalid return code from buildpack 
 
Merci

**Comment by btrd** [comment]
@sisitototest Concernant la version SASS comme l'indique le ticket elle n'est pas finalisé pour le moment et reste en projet.

Votre erreur trouve l'origine à cet endroit `config/environments/production.rb:68`
https://github.com/betagouv/civilsdeladefense/blob/production/config/environments/production.rb#L68
```ruby
smtp_uri = URI(ENV['SMTP_URL'])
```

Il est nécessaire de définir cette variable d'environnement. Je me notes de mettre à jour le README pour que ce soit plus clair.

N'hésitez pas à ouvrir un nouveau ticket si vous rencontrez d'autres problèmes.

**Comment by btrd** [comment]
La version SaaS n'est plus d'actualité
